import { Market } from "@/features/market/types"

export const MOCK_POOLS: Market[] = [
  {
    id: 0,
    question: "Will BTC reach $500k USD by 2030?",
    status: "Open",
    totalYesPrincipal: 1200,
    totalNoPrincipal: 800,
    totalTVL: 2000,
    currentExchangeRate: 1.12,
    bettingDeadline: null,
    winningSide: null,
    yesOdds: 60,
    noOdds: 40,
  },
  {
    id: 1,
    question: "Will Donald Trump win the 2028 presidential election?",
    status: "Open",
    totalYesPrincipal: 500,
    totalNoPrincipal: 1500,
    totalTVL: 2000,
    currentExchangeRate: 1.08,
    bettingDeadline: "2028-11-01",
    winningSide: null,
    yesOdds: 25,
    noOdds: 75,
  },
  {
    id: 2,
    question: "Will ETH flip BTC before 2026?",
    status: "Resolved",
    totalYesPrincipal: 300,
    totalNoPrincipal: 700,
    totalTVL: 1000,
    currentExchangeRate: 1.20,
    bettingDeadline: "2025-12-31",
    winningSide: "NO",
    yesOdds: 30,
    noOdds: 70,
  },
  {
    id: 3,
    question: "Will Argentina win the 2026 World Cup?",
    status: "Open",
    totalYesPrincipal: 900,
    totalNoPrincipal: 600,
    totalTVL: 1500,
    currentExchangeRate: 1.05,
    bettingDeadline: "2026-07-15",
    winningSide: null,
    yesOdds: 60,
    noOdds: 40,
  },
  {
    id: 4,
    question: "Will the Flow blockchain enter the top 10 by market cap in 2025?",
    status: "Resolved",
    totalYesPrincipal: 400,
    totalNoPrincipal: 100,
    totalTVL: 500,
    currentExchangeRate: 1.15,
    bettingDeadline: "2025-12-31",
    winningSide: "YES",
    yesOdds: 80,
    noOdds: 20,
  },
  {
    id: 5,
    question: "Will Apple release AR glasses before 2027?",
    status: "Cancelled",
    totalYesPrincipal: 200,
    totalNoPrincipal: 200,
    totalTVL: 400,
    currentExchangeRate: 1.03,
    bettingDeadline: "2026-06-01",
    winningSide: null,
    yesOdds: 50,
    noOdds: 50,
  },
]