// import { Pool } from "@/features/pool/types"

// const now = Date.now() / 1000

// export const MOCK_POOLS: Pool[] = [
//   {
//     id: 4,
//     name: "Weekly Pool #2",
//     status: "Open",
//     capacity: 100,
//     currentUserCount: 0,
//     depositAmount: 100,
//     activeDuration: 2592000,
//     winnerCount: 5,
//     totalPrincipal: 0,
//     yieldAPR: 0.07,
//     adminFeePercentage: 0.01,
//     createdAt: 1774893795,
//     activatedAt: null,
//     completedAt: null,
//   },
//   {
//     id: 7,
//     name: "Yearly Pool #1",
//     status: "Open",
//     capacity: 100,
//     currentUserCount: 0,
//     depositAmount: 100,
//     activeDuration: 2592000,
//     winnerCount: 20,
//     totalPrincipal: 0,
//     yieldAPR: 0.07,
//     adminFeePercentage: 0.01,
//     createdAt: 1774894092,
//     activatedAt: null,
//     completedAt: null,
//   },
//   {
//     id: 5,
//     name: "Monthly Pool #1",
//     status: "Open",
//     capacity: 100,
//     currentUserCount: 0,
//     depositAmount: 100,
//     activeDuration: 2592000,
//     winnerCount: 10,
//     totalPrincipal: 0,
//     yieldAPR: 0.07,
//     adminFeePercentage: 0.01,
//     createdAt: 1774893858,
//     activatedAt: null,
//     completedAt: null,
//   },
//   {
//     id: 3,
//     name: "Weekly Pool #1",
//     status: "Open",
//     capacity: 100,
//     currentUserCount: 0,
//     depositAmount: 100,
//     activeDuration: 2592000,
//     winnerCount: 5,
//     totalPrincipal: 0,
//     yieldAPR: 0.07,
//     adminFeePercentage: 0.01,
//     createdAt: 1774893737,
//     activatedAt: null,
//     completedAt: null,
//   },
// ];
