import { Market } from "@/features/market/types"

export const MOCK_MARKETS: Market[] = [
  {
    id: 0,
    question: "Apakah BTC mencapai $500k USD pada 2030?",
    status: "Open",
    totalYesPrincipal: 1200,
    totalNoPrincipal: 800,
    totalTVL: 2000,
    currentExchangeRate: 1.12,
    bettingDeadline: null,
    winningSide: null,
    yesOdds: 60,
    noOdds: 40,
  },
  {
    id: 1,
    question: "Apakah Donald Trump memenangkan pilpres 2028?",
    status: "Open",
    totalYesPrincipal: 500,
    totalNoPrincipal: 1500,
    totalTVL: 2000,
    currentExchangeRate: 1.08,
    bettingDeadline: "2028-11-01",
    winningSide: null,
    yesOdds: 25,
    noOdds: 75,
  },
  {
    id: 2,
    question: "Apakah ETH flippening BTC sebelum 2026?",
    status: "Resolved",
    totalYesPrincipal: 300,
    totalNoPrincipal: 700,
    totalTVL: 1000,
    currentExchangeRate: 1.20,
    bettingDeadline: "2025-12-31",
    winningSide: "NO",
    yesOdds: 30,
    noOdds: 70,
  },
  {
    id: 3,
    question: "Apakah Argentina juara Piala Dunia 2026?",
    status: "Open",
    totalYesPrincipal: 900,
    totalNoPrincipal:  600,
    totalTVL: 1500,
    currentExchangeRate: 1.05,
    bettingDeadline: "2026-07-15",
    winningSide: null,
    yesOdds: 60,
    noOdds: 40,
  },
  {
    id: 4,
    question: "Apakah Flow blockchain masuk top 10 market cap 2025?",
    status: "Resolved",
    totalYesPrincipal: 400,
    totalNoPrincipal: 100,
    totalTVL: 500,
    currentExchangeRate: 1.15,
    bettingDeadline: "2025-12-31",
    winningSide: "YES",
    yesOdds: 80,
    noOdds: 20,
  },
  {
    id: 5,
    question: "Apakah Apple merilis AR glasses sebelum 2027?",
    status: "Cancelled",
    totalYesPrincipal: 200,
    totalNoPrincipal: 200,
    totalTVL: 400,
    currentExchangeRate: 1.03,
    bettingDeadline: "2026-06-01",
    winningSide: null,
    yesOdds: 50,
    noOdds: 50,
  },
]
